# Parameters of input image

INPUT_IMAGE_WIDTH_PIXEL = 1224
INPUT_IMAGE_HEIGHT_PIXEL = 1024

BBOX_VALID_BOUNDARY_OFFSET = 20
BBOX_VALID_BOUNDARY_X_LEFT = BBOX_VALID_BOUNDARY_OFFSET
BBOX_VALID_BOUNDARY_X_RIGHT = INPUT_IMAGE_WIDTH_PIXEL - BBOX_VALID_BOUNDARY_X_LEFT
BBOX_VALID_BOUNDARY_Y_UP = BBOX_VALID_BOUNDARY_OFFSET
BBOX_VALID_BOUNDARY_Y_DOWN = INPUT_IMAGE_HEIGHT_PIXEL - BBOX_VALID_BOUNDARY_Y_UP
